# Generated by Django 3.0.4 on 2020-03-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200328_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.CharField(choices=[('0', 'Cheese'), ('1', '1 Topping'), ('2', '2 Toppings'), ('3', '3 Toppings'), ('5', 'Special')], default='CH', max_length=15),
        ),
    ]
